{"uuid": "ab55a354-082e-4f88-988b-9589b62995eb", "children": ["535053e7-e392-4d34-a1c1-7457f46c7912"], "befores": [{"name": "start_appium_desired", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.dayhr' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command ''D:\\\\ruanjian\\\\android SDK\\\\platform-tools\\\\adb.exe' -P 5037 -s 35987d7f shell am start -W -n com.dayhr/com.dayhr.login.activity.LoginActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 255'; Stderr: 'Security exception: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.dayhr/.login.activity.LoginActivity } from null (pid=5001, uid=2000) not exported from uid 10296\r\n\r\njava.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.dayhr/.login.activity.LoginActivity } from null (pid=5001, uid=2000) not exported from uid 10296\r\n\tat com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1089)\r\n\tat com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:789)\r\n\tat com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:588)\r\n\tat com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1392)\r\n\tat com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:519)\r\n\tat com.android.server.wm.ActivityTaskManagerService.startActivityAndWait(ActivityTaskManagerService.java:1264)\r\n\tat com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:3581)\r\n\tat com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:513)\r\n\tat com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:172)\r\n\tat android.os.ShellCommand.exec(ShellCommand.java:111)\r\n\tat com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10093)\r\n\tat android.os.Binder.shellCommand(Binder.java:881)\r\n\tat android.os.Binder.onTransact(Binder.java:765)\r\n\tat android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4727)\r\n\tat com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2799)\r\n\tat android.os.Binder.execTransactInternal(Binder.java:1021)\r\n\tat android.os.Binder.execTransact(Binder.java:994)'; Code: '255'\n\n", "trace": "  File \"D:\\daima\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\daima\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\daima\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Appium_AutoTest-Mobile\\testcase\\conftest.py\", line 45, in start_appium_desired\n    driver = appium_desired_caps(host, port)\n  File \"D:\\Appium_AutoTest-Mobile\\base\\DesireCaps.py\", line 43, in appium_desired_caps\n    driver = webdriver.Remote('http://%s:%s/wd/hub' % (host, port), desired_caps)  # IP地址是Appium中的监听地址\n  File \"D:\\daima\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 156, in __init__\n    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\daima\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1618543264783, "stop": 1618543278816}], "start": 1618543264783, "stop": 1618543278877}