2021-04-06 10:01:46,120 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 10:01:46,135 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 10:04:38,913 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 10:04:38,925 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 10:05:15,095 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 10:05:15,095 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 11:32:10,239 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 11:32:10,251 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 11:43:16,290 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 11:43:16,339 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 11:44:22,785 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 11:44:22,796 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 11:49:22,557 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 11:49:22,575 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 12:10:11,903 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 12:10:11,939 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 12:11:10,407 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 12:11:10,417 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 12:11:35,657 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 12:11:35,672 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 12:11:35,680 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 12:11:35,683 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 12:11:35,776 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 12:11:35,787 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 13:35:27,745 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:35:27,749 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:35:27,753 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:35:27,757 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:35:27,796 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 13:35:27,807 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 13:39:01,329 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:39:01,334 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:39:01,338 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:39:01,342 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:39:01,404 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 13:39:01,438 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 13:39:25,551 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:39:25,565 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:39:25,580 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:39:25,592 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:39:25,683 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 13:39:25,696 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 13:39:36,177 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:39:36,189 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:39:36,203 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:39:36,216 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:39:36,306 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 13:39:36,321 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 13:42:36,449 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:42:36,453 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:42:36,457 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:42:36,461 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:42:56,185 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:42:56,189 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:42:56,194 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 13:42:56,197 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 13:42:56,236 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 13:42:56,246 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:04:35,022 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:04:35,038 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:04:35,043 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:04:35,047 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:06:58,189 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:06:58,193 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:06:58,198 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:06:58,201 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:10:13,678 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:10:13,691 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:10:13,705 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:10:13,717 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:10:13,830 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:10:13,844 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:12:59,955 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:12:59,959 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:12:59,962 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:12:59,965 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:13:00,008 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:13:00,019 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:14:10,929 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:14:10,933 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:14:10,937 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:14:10,941 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:14:10,979 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:14:10,990 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:14:40,462 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:14:40,466 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:14:40,469 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:14:40,473 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:14:40,516 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:14:40,527 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:15:05,912 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:15:05,916 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:15:05,921 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:15:05,924 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:15:05,964 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:15:05,976 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:23:08,877 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:23:08,882 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:23:08,887 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:23:08,890 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:23:08,927 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:23:08,938 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:23:27,959 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:23:27,962 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:23:27,967 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:23:27,971 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:23:28,010 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:23:28,021 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:24:31,386 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:24:31,390 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:24:31,394 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:24:31,398 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:24:31,434 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:24:31,445 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:27:29,343 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:27:29,347 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:27:29,351 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:27:29,355 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:27:29,391 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:27:29,402 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:28:00,192 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:28:00,196 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:28:00,200 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:28:00,204 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:28:00,242 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:28:00,253 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:29:35,726 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:29:35,730 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:29:35,734 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:29:35,743 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:29:35,781 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:29:35,791 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:34:56,904 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:34:56,908 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:34:56,912 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:34:56,916 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:34:56,952 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:34:56,965 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:36:53,510 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:36:53,514 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:36:53,518 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:36:53,522 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:36:53,560 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:36:53,573 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:41:51,863 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:41:51,867 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:41:51,871 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:41:51,875 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:41:51,914 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:41:51,926 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:46:48,497 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:46:48,501 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:46:48,506 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:46:48,509 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:46:48,551 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:46:48,563 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:47:31,987 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:47:31,991 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:47:31,998 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:47:32,002 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:47:32,043 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:47:32,053 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:49:03,942 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:49:03,946 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:49:03,950 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:49:03,954 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:49:04,002 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 14:49:06,006 - start_appium - INFO - port 4723 is not used
2021-04-06 14:49:08,417 - start_appium - INFO - [36minfo[39m: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
2021-04-06 14:49:08,417 - start_appium - INFO - [36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
2021-04-06 14:49:08,417 - start_appium - INFO - 启动成功：启动参数是：host为127.0.0.1,port为4723,bpport为4724,udid为192.168.0.101:5555
2021-04-06 14:49:13,417 - start_appium - INFO - port 4723 is used!
2021-04-06 14:52:12,602 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:52:12,606 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:52:12,610 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:52:12,614 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:52:12,679 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 14:52:14,683 - start_appium - INFO - port 4723 is not used
2021-04-06 14:52:16,923 - start_appium - INFO - [36minfo[39m: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
2021-04-06 14:52:16,923 - start_appium - INFO - [36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
2021-04-06 14:52:16,923 - start_appium - INFO - 启动成功：启动参数是：host为127.0.0.1,port为4723,bpport为4724,udid为192.168.0.101:5555
2021-04-06 14:52:21,923 - start_appium - INFO - port 4723 is used!
2021-04-06 14:52:51,684 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:52:51,688 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:52:51,693 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:52:51,696 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:52:51,740 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 14:52:51,741 - start_appium - INFO - port 4723 is used!
2021-04-06 14:52:56,742 - start_appium - INFO - port 4723 is used!
2021-04-06 14:53:18,372 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 14:53:18,377 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 14:53:18,380 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 14:53:18,381 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 14:53:20,165 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 14:53:20,166 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 14:53:20,166 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 14:53:22,596 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 14:53:22,596 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 14:53:22,597 - operate - DEBUG - 该关键字是click_btn
2021-04-06 14:53:23,698 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 14:53:23,698 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 14:53:23,699 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 14:53:24,777 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 14:53:26,665 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:53:26,716 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:56:23,868 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:56:23,872 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:56:23,875 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:56:23,879 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:56:23,950 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 14:56:23,950 - start_appium - INFO - port 4723 is used!
2021-04-06 14:56:28,950 - start_appium - INFO - port 4723 is used!
2021-04-06 14:56:46,911 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 14:56:46,915 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 14:56:46,919 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 14:56:46,920 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 14:56:49,074 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 14:56:49,074 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 14:56:49,075 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 14:56:50,939 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 14:56:50,939 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 14:56:50,940 - operate - DEBUG - 该关键字是click_btn
2021-04-06 14:56:51,795 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 14:56:51,795 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 14:56:51,796 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 14:56:53,807 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 14:56:55,153 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:56:55,240 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 14:58:48,990 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:58:48,994 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:58:48,998 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 14:58:49,000 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 14:58:49,044 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 14:58:49,044 - start_appium - INFO - port 4723 is used!
2021-04-06 14:58:54,045 - start_appium - INFO - port 4723 is used!
2021-04-06 14:59:14,526 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 14:59:14,531 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 14:59:14,535 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 14:59:14,537 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 14:59:16,384 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 14:59:16,384 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 14:59:16,385 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 14:59:18,384 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 14:59:18,385 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 14:59:18,385 - operate - DEBUG - 该关键字是click_btn
2021-04-06 14:59:19,033 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 14:59:19,033 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 14:59:19,034 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 14:59:20,764 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 14:59:21,575 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 14:59:21,598 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 15:15:49,742 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 15:15:49,760 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 15:15:49,764 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 15:15:49,768 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 15:15:54,899 - start_appium - INFO - 获取的devices信息udid:[]
2021-04-06 15:15:55,675 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 15:15:55,684 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 15:16:56,056 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 15:16:56,062 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 15:16:56,067 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 15:16:56,073 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 15:16:56,115 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 15:16:58,119 - start_appium - INFO - port 4723 is not used
2021-04-06 15:17:25,013 - start_appium - INFO - [36minfo[39m: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
2021-04-06 15:17:25,013 - start_appium - INFO - [36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
2021-04-06 15:17:25,013 - start_appium - INFO - 启动成功：启动参数是：host为127.0.0.1,port为4723,bpport为4724,udid为192.168.0.101:5555
2021-04-06 15:17:30,014 - start_appium - INFO - port 4723 is used!
2021-04-06 15:18:13,323 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 15:18:13,327 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 15:18:13,331 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 15:18:13,335 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 15:18:13,374 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 15:18:13,375 - start_appium - INFO - port 4723 is used!
2021-04-06 15:18:18,375 - start_appium - INFO - port 4723 is used!
2021-04-06 15:18:26,508 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 15:18:26,519 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 15:20:08,208 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 15:20:08,211 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 15:20:08,215 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 15:20:08,219 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 15:20:08,273 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 15:20:08,274 - start_appium - INFO - port 4723 is used!
2021-04-06 15:20:13,274 - start_appium - INFO - port 4723 is used!
2021-04-06 15:20:38,417 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 15:20:38,421 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 15:20:38,426 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 15:20:38,427 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 15:20:40,497 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 15:20:40,497 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 15:20:40,498 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 15:20:42,446 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 15:20:42,447 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 15:20:42,447 - operate - DEBUG - 该关键字是click_btn
2021-04-06 15:20:43,536 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 15:20:43,536 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 15:20:43,537 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 15:20:45,348 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 15:20:46,025 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 15:20:46,050 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 15:39:21,839 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 15:39:21,842 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 15:39:21,847 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 15:39:21,852 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 15:39:21,910 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 15:39:21,910 - start_appium - INFO - port 4723 is used!
2021-04-06 15:39:26,911 - start_appium - INFO - port 4723 is used!
2021-04-06 15:39:44,286 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 15:39:44,290 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 15:39:44,293 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 15:39:44,294 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 15:39:45,767 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 15:39:45,767 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 15:39:45,768 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 15:39:48,072 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 15:39:48,072 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 15:39:48,073 - operate - DEBUG - 该关键字是click_btn
2021-04-06 15:39:48,974 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 15:39:48,974 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 15:39:48,975 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 15:39:50,440 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 15:39:51,258 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 15:39:51,290 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 16:10:40,870 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 16:10:43,728 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 16:10:55,454 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 16:10:58,906 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 16:11:42,792 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 16:11:45,658 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 16:13:51,754 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 16:13:54,266 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 16:26:15,463 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:26:15,467 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:26:15,471 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:26:15,474 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:26:15,561 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 16:26:15,562 - start_appium - INFO - port 4723 is used!
2021-04-06 16:26:20,563 - start_appium - INFO - port 4723 is used!
2021-04-06 16:26:36,993 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 16:26:37,000 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 16:26:37,006 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 16:26:37,007 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 16:26:39,092 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 16:26:39,092 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 16:26:39,093 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 16:26:40,848 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 16:26:40,848 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 16:26:40,849 - operate - DEBUG - 该关键字是click_btn
2021-04-06 16:26:41,494 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 16:26:41,494 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 16:26:41,495 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 16:26:42,470 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 16:26:43,032 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 16:26:43,082 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 16:39:19,270 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:39:19,274 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:39:19,278 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:39:19,282 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:39:19,322 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 16:39:19,323 - start_appium - INFO - port 4723 is used!
2021-04-06 16:42:37,313 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:42:37,317 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:42:37,321 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:42:37,325 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:42:37,371 - start_appium - INFO - 获取的devices信息udid:['192.168.0.101:5555']
2021-04-06 16:42:37,371 - start_appium - INFO - port 4723 is used!
2021-04-06 16:42:42,372 - start_appium - INFO - port 4723 is used!
2021-04-06 16:42:59,906 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 16:42:59,910 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 16:42:59,914 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 16:42:59,915 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 16:43:01,430 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 16:43:01,430 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 16:43:01,431 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 16:43:03,289 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 16:43:03,289 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 16:43:03,290 - operate - DEBUG - 该关键字是click_btn
2021-04-06 16:43:03,934 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 16:43:03,934 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 16:43:03,935 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 16:43:05,205 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 16:43:06,413 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 16:43:09,831 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 16:52:21,747 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:52:21,754 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:52:21,759 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:52:21,763 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:52:26,203 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:52:26,208 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:52:26,212 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:52:26,216 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:55:37,098 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:55:37,102 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:55:37,106 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:55:37,109 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:55:37,662 - start_appium - INFO - 获取的devices信息udid:[]
2021-04-06 16:55:37,770 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 16:55:46,298 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 16:56:02,160 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:56:02,165 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:56:02,169 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:56:02,172 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:56:05,236 - start_appium - INFO - 获取的devices信息udid:[]
2021-04-06 16:56:05,276 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 16:56:08,301 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 16:58:15,428 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:58:15,432 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:58:15,436 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 16:58:15,440 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 16:58:26,077 - start_appium - INFO - 获取的devices信息udid:[]
2021-04-06 16:58:26,129 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 16:58:28,972 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 17:01:38,151 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:01:38,155 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:01:38,160 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:01:38,164 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:01:38,206 - start_appium - INFO - 获取的devices信息udid:['127.0.0.1:62001']
2021-04-06 17:01:38,207 - start_appium - INFO - port 4723 is used!
2021-04-06 17:01:43,207 - start_appium - INFO - port 4723 is used!
2021-04-06 17:02:03,396 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:02:03,400 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:02:03,405 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:02:03,406 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:02:05,070 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 17:02:05,070 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 17:02:05,070 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:02:07,108 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 17:02:07,109 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 17:02:07,109 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:02:07,722 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 17:02:07,723 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 17:02:07,724 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 17:02:09,101 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 17:02:10,627 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 17:02:13,720 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 17:03:17,340 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:03:17,344 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:03:17,348 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:03:17,352 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:03:17,394 - start_appium - INFO - 获取的devices信息udid:['127.0.0.1:62001']
2021-04-06 17:03:17,395 - start_appium - INFO - port 4723 is used!
2021-04-06 17:03:22,396 - start_appium - INFO - port 4723 is used!
2021-04-06 17:03:40,791 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:03:40,795 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:03:40,799 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:03:40,800 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:03:42,495 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 17:03:42,495 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 17:03:42,496 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:03:44,470 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 17:03:44,470 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 17:03:44,471 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:03:45,107 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 17:03:45,107 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 17:03:45,107 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 17:03:46,435 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 17:03:47,884 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 17:03:50,992 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 17:06:43,247 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:06:43,268 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数2，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}, {'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:06:43,273 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:06:43,276 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数2，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}, {'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:06:43,349 - start_appium - INFO - 获取的devices信息udid:['127.0.0.1:62001']
2021-04-06 17:06:43,350 - start_appium - INFO - port 4723 is used!
2021-04-06 17:06:48,351 - start_appium - INFO - port 4723 is used!
2021-04-06 17:07:07,304 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:07:07,308 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:07:07,311 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:07:07,312 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:07:08,917 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 17:07:08,918 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 17:07:08,918 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:07:10,811 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 17:07:10,811 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 17:07:10,812 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:07:11,449 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 17:07:11,449 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 17:07:11,450 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 17:07:12,284 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 17:07:17,025 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:07:17,025 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:07:17,025 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:07:17,026 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:07:18,667 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 17:07:18,667 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 17:07:18,668 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:07:20,883 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 17:07:20,883 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 17:07:20,884 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:07:21,514 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 17:07:21,514 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 17:07:21,515 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 17:07:42,577 - Base_Page - ERROR - toast获取信息失败， 错误信息Message: 

2021-04-06 17:07:43,919 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 17:07:48,064 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 17:08:22,542 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:08:22,546 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数2，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}, {'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:08:22,552 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:08:22,555 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数2，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}, {'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:08:22,603 - start_appium - INFO - 获取的devices信息udid:['127.0.0.1:62001']
2021-04-06 17:08:22,603 - start_appium - INFO - port 4723 is used!
2021-04-06 17:08:27,605 - start_appium - INFO - port 4723 is used!
2021-04-06 17:08:46,523 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:08:46,527 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:08:46,531 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:08:46,532 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:08:46,569 - Base_Page - ERROR - 没有找到该元素Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

2021-04-06 17:08:52,394 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:08:52,395 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:08:52,395 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:08:52,399 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:08:52,414 - Base_Page - ERROR - 没有找到该元素Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

2021-04-06 17:08:54,851 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 17:08:58,207 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 17:09:06,527 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:09:06,532 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数2，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}, {'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:09:06,536 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:09:06,540 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数2，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}, {'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:09:06,585 - start_appium - INFO - 获取的devices信息udid:['127.0.0.1:62001']
2021-04-06 17:09:06,586 - start_appium - INFO - port 4723 is used!
2021-04-06 17:09:11,586 - start_appium - INFO - port 4723 is used!
2021-04-06 17:09:30,533 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:09:30,537 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:09:30,541 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:09:30,542 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:09:32,164 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 17:09:32,164 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 17:09:32,165 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:09:34,222 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 17:09:34,223 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 17:09:34,223 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:09:34,867 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 17:09:34,867 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 17:09:34,868 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 17:09:36,203 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 17:09:40,997 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:09:40,998 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:09:40,998 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:09:40,999 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:09:42,590 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 17:09:42,590 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 17:09:42,591 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:09:44,620 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 17:09:44,620 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 17:09:44,621 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:09:45,254 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 17:09:45,254 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 17:09:45,255 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 17:09:55,238 - Base_Page - ERROR - toast获取信息失败， 错误信息Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

2021-04-06 17:09:56,579 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 17:10:00,057 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 17:18:13,286 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:18:13,290 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数2，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}, {'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:18:54,422 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:18:54,423 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数2，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}, {'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:19:11,264 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:19:11,264 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数2，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}, {'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:19:45,041 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:19:45,041 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数2，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=13129559867,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}, {'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=13129559867,password=xiaohai1', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:25:32,618 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:25:32,622 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=1312,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:25:32,626 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:25:32,630 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=1312,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:25:32,676 - start_appium - INFO - 获取的devices信息udid:['127.0.0.1:62001']
2021-04-06 17:25:32,677 - start_appium - INFO - port 4723 is used!
2021-04-06 17:25:37,677 - start_appium - INFO - port 4723 is used!
2021-04-06 17:25:57,041 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=1312,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:25:57,045 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:25:57,050 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:25:57,051 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:25:58,675 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 17:25:58,675 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 17:25:58,676 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:26:00,713 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 17:26:00,713 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 17:26:00,714 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:26:01,330 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 17:26:01,330 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 17:26:01,331 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 17:26:02,655 - Base_Page - INFO - 获取toast内容为：账号或密码输入错误，请重新输入
2021-04-06 17:26:04,247 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 17:26:07,461 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 17:26:36,971 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:26:36,974 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=1312,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:26:36,978 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:26:36,982 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=1312,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:26:37,025 - start_appium - INFO - 获取的devices信息udid:['127.0.0.1:62001']
2021-04-06 17:26:37,026 - start_appium - INFO - port 4723 is used!
2021-04-06 17:26:42,027 - start_appium - INFO - port 4723 is used!
2021-04-06 17:27:00,142 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=1312,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:27:00,148 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:27:00,152 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:27:00,153 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:27:01,889 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 17:27:01,890 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.dayhr:id/password_edittext'}
2021-04-06 17:27:01,890 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:27:03,927 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 17:27:03,927 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.dayhr:id/login_button'}
2021-04-06 17:27:03,928 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:27:06,185 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 17:27:09,207 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 17:35:14,589 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:35:14,593 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=1312,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:35:14,598 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:35:14,602 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=1312,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:35:14,652 - start_appium - INFO - 获取的devices信息udid:['127.0.0.1:62001']
2021-04-06 17:35:14,653 - start_appium - INFO - port 4723 is used!
2021-04-06 17:35:19,654 - start_appium - INFO - port 4723 is used!
2021-04-06 17:35:37,071 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_001', '是否运行': 'y', '用例名称': '登录失败', '测试数据': 'username=1312,password=123456', '期望结果': '错误', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:35:37,079 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:35:37,086 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.dayhr:id/account_editText'}
2021-04-06 17:35:37,087 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:36:23,590 - Base_Page - ERROR - 没有找到该元素Message: 

2021-04-06 17:36:25,073 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 17:46:48,062 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:46:48,066 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=17700000007,password=12345678', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:46:48,070 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:46:48,074 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=17700000007,password=12345678', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:46:48,117 - start_appium - INFO - 获取的devices信息udid:['127.0.0.1:62001']
2021-04-06 17:46:48,117 - start_appium - INFO - port 4723 is used!
2021-04-06 17:46:53,118 - start_appium - INFO - port 4723 is used!
2021-04-06 17:47:09,860 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=17700000007,password=12345678', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:47:09,864 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:47:09,869 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.gemini.cloud.client:id/et_account'}
2021-04-06 17:47:09,870 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:47:11,862 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 17:47:11,863 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.gemini.cloud.client:id/et_password'}
2021-04-06 17:47:11,863 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:47:13,599 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 17:47:13,600 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.gemini.cloud.client:id/btn_login'}
2021-04-06 17:47:13,601 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:47:14,242 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 17:47:14,243 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 17:47:14,243 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 17:47:35,417 - Base_Page - ERROR - toast获取信息失败， 错误信息Message: 

2021-04-06 17:47:36,691 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 17:47:39,970 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
2021-04-06 17:54:29,949 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:54:29,954 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=17700000007,password=12345678', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:54:29,958 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取TestCases表测试个数1, 数据内容[{'序号': 1.0, '描述': '登录测试', 'TC_ID': 'TC_Login', '是否运行': 'y', '备注': '登录功能测试'}]
2021-04-06 17:54:29,962 - D:\appiumdm\Appium_AutoTest\utils\LogUtil.py - DEBUG - 获取CasesData表测试个数1，数据内容[{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=17700000007,password=12345678', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}]
2021-04-06 17:54:30,006 - start_appium - INFO - 获取的devices信息udid:['127.0.0.1:62001']
2021-04-06 17:54:30,007 - start_appium - INFO - port 4723 is used!
2021-04-06 17:54:35,007 - start_appium - INFO - port 4723 is used!
2021-04-06 17:54:51,032 - TestKeywords - INFO - 执行用例内容{'TC_ID': 'TC_Login', 'CASE_ID': 'Case_002', '是否运行': 'y', '用例名称': '登录成功', '测试数据': 'username=17700000007,password=12345678', '期望结果': '登陆', '备注': '登录功能测试', '描述': '登录测试'}
2021-04-06 17:54:51,044 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS001', '步骤名称': '输入用户名', '操作': 'text', '元素名称': 'El_account_editText', '数据': 'username'}
2021-04-06 17:54:51,051 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_account_editText', '定位类型': 'id', '元素信息': 'com.gemini.cloud.client:id/et_account'}
2021-04-06 17:54:51,053 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:54:53,046 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS002', '步骤名称': '输入密码', '操作': 'text', '元素名称': 'El_password_edittext', '数据': 'password'}
2021-04-06 17:54:53,046 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_password_edittext', '定位类型': 'id', '元素信息': 'com.gemini.cloud.client:id/et_password'}
2021-04-06 17:54:53,048 - operate - DEBUG - 该关键字是by_id_send_keys
2021-04-06 17:54:54,747 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS003', '步骤名称': '点击同意协议', '操作': 'click', '元素名称': 'El_agreement', '数据': ''}
2021-04-06 17:54:54,747 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_agreement', '定位类型': 'id', '元素信息': 'com.gemini.cloud.client:id/iv_agreement'}
2021-04-06 17:54:54,748 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:54:55,396 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS004', '步骤名称': '点击登录', '操作': 'click', '元素名称': 'El_login_button', '数据': ''}
2021-04-06 17:54:55,396 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_login_button', '定位类型': 'id', '元素信息': 'com.gemini.cloud.client:id/btn_login'}
2021-04-06 17:54:55,397 - operate - DEBUG - 该关键字是click_btn
2021-04-06 17:54:55,934 - operate - DEBUG - 执行步骤{'TC_ID': 'TC_Login', '步骤ID': 'TS005', '步骤名称': '获取验证', '操作': 'verify_toast', '元素名称': 'El_toast', '数据': ''}
2021-04-06 17:54:55,934 - operate - DEBUG - 元素信息{'TC_ID': 'TC_Login', '元素名称': 'El_toast', '定位类型': 'xpath', '元素信息': '//*[contains(@text,\'" + text + "\')]'}
2021-04-06 17:54:55,935 - operate - DEBUG - 该关键字是assert_toast_result
2021-04-06 17:55:20,567 - Base_Page - ERROR - toast获取信息失败， 错误信息Message: 

2021-04-06 17:55:21,805 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\result
2021-04-06 17:55:24,844 - allure_generate - INFO - 报告地址D:\appiumdm\Appium_AutoTest\report\html
